# Generated by Django 6.0.3 on 2026-03-12 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Correct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Incorrect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                (
                    "correct_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.correct"
                    ),
                ),
            ],
        ),
    ]
