# Generated by Django 6.0.3 on 2026-03-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incorrect",
            old_name="correct_id",
            new_name="correct",
        ),
    ]
